### ISSUE TITLE
Question about the comparison between ESPNet and ESPNetv2 on your paper.

### ISSUE THREAD

**Issue by msson** [sacmehta/ESPNetv2#12]
Hi,

I have a question about the graph (It's on 4.2 Semantic segmentation -- Results -- (a) ESPNet vs. ESPNetv2 (validation set)) on your ESPNetv2 paper.
There are 6 points in the graph, 3 is for ESPNetv2 and the others' for ESPNet.
I am wondering those points' parameters are p=2, q=3,5,8 for ESPNet and s=0.5,1.0,1.5 for ESPNetv2 or any other parameters.

Thanks.

**Comment by sacmehta** [comment]
Yes, you are correct.

**Comment by msson** [comment]
Thanks!
