### ISSUE TITLE
How to train own dataset?

### ISSUE THREAD

**Issue by pentaris** [sacmehta/ESPNetv2#13]
Hello, I'm a student studying machine running.

I found ESPNet v2 after looking for a network of real time semantic segmentation processing on TX2.

I don't have the cityscapes dataset, so I want to do training with own dataset.

I'm a beginner about machine running.

Could you provide a tutorial that trains to own dataset?

 Thank you in advance.

**Comment by sacmehta** [comment]
Training has two parts:
i) Data preparation: Here, you check if the data is in write format or not. Also, you compute class imbalance weights if your dataset is imbalanced. Please see loadData.py file for more details. It is pretty simple and accepts two text files: one for training and one for validation. You can create these files easily as these contains mapping between RGB image and Segmentation mask (ground truth) in comma separated form. Note that one line per image pair.

ii) Training: One you are done with this part i), you can start training your model on your dataset. You need to adjust the number of classes in the main.py file. Please see main.py file for more details. It should be straight forward.

Let me know if you are still encountering any issues.

**Comment by pentaris** [comment]
Thank you for your kind answers.

I would like to ask about writing two text files 'train.txt' and 'val.txt'.

Does train.txt and val.txt create a path to the image to be trained and validated?

```
data_dict = dict()
data_dict['trainIm'] = self.trainImList
data_dict['trainAnnot'] = self.trainAnnotList
data_dict['valIm'] = self.valImList
data_dict['valAnnot'] = self.valAnnotList

data_dict['mean'] = self.mean
data_dict['std'] = self.std
data_dict['classWeights'] = self.classWeights
```

Or is it necessary to write trainIm, trainAnnot, valIm, ValAnnot, mean etc. separated by commas and line by line, as in the code?

It would be helpful to have a sample to refer to.

Thank you for your answer to the my stupid question.

**Comment by pentaris** [comment]
I tried to train in the way you showed me.

However, I encountered such an error during training.

There are 12 dataset classes, and the size is 480 x 320.

I modified the code a little, but is there something missing?

![image](https://user-images.githubusercontent.com/20432143/53085248-c96ead00-3545-11e9-9ade-ddb61b4100b3.png)

**Comment by wangyihuan123** [comment]
I encountered the similar issue before. After I prepare the data image/annotation with 1024x512 resolution, the problem disappeared. I can't remember very clearly.  You can have a try.
