### ISSUE TITLE
Cityscape Dataset Error

### ISSUE THREAD

**Issue by monk42** [sacmehta/ESPNetv2#2]
Hi, thank you for your work and for open sourcing your code!
When I run your code ,i have a problem:
Firstly, I have used this code (https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py) to convert the label images to trainIDs, but i still got error!
![image](https://user-images.githubusercontent.com/33028017/49571024-1ee9e380-f973-11e8-869b-7a8310cd1481.png)
Can give me some advices to solve this error?

**Comment by sacmehta** [comment]
I think you have 255 in your labels. Please check.

**Comment by monk42** [comment]
yes！ I debug the code, found it has 255 label.  But I don’t know how to deal with this label!

**Comment by sacmehta** [comment]
I have updated the files. See if that resolves the issue/

**Comment by monk42** [comment]
thanks,
I understand your approach， but you make a mistake, I think your updated scripts should precede unique_values = np.unique(label_img) .

But I get a new problem. The 255 label often ignored in training,  when change it to a background class whether it will affect training?

**Comment by sacmehta** [comment]
All the results reported in our paper is with this strategy and I don’t think it will change the performance. Moreover, Cityscapes ignore background, including label 255, in their evaluations.

P.S.: Label 255 indicates that pixels corresponding to this region are not useful for the task.

**Comment by monk42** [comment]
thanks，I'll learn more about it.
