### ISSUE TITLE
About Power consumption

### ISSUE THREAD

**Issue by stigma0617** [sacmehta/ESPNetv2#26]
First, I'm impressed by your good work.

I wonder how to measure power consumption on TX board.

I can't find more details about measuring power consumption in your paper.

Thanks

**Comment by sacmehta** [comment]
Please ask on NVIDIA support page.

**Comment by stigma0617** [comment]
@sacmehta , 

I wonder how to measure and compare power consumption in your paper.

For public confidence, your paper is needed to reveal how to measure and compare energy fairly.

**Comment by sacmehta** [comment]
What do you mean by public confidence?

NVIDIA TX2 is manufactured by NVIDIA and "not me". So, you need to ask them how to measure these metrics. They can provide you much better support than me.

**Comment by stigma0617** [comment]
@sacmehta Hi, 

Did NVIDIA directly measure the results in your paper?

I just want to know how "you" measure power consumption. 

For examples, In [SqueezeDet](https://arxiv.org/abs/1612.01051)  paper, the author said that they measure power consumption by nvidia-smi with 100ms interval. 

I just want to know your measuring method in order to reproduce your results on my TX2 board.

**Comment by sacmehta** [comment]
You can measure power on desktop GPUs using nvidia-smi and we also used the same on Desktop GPu. However, nvidia-smi doesn’t work on TX2. Please post on nvidia forums for more help.

**Comment by sacmehta** [comment]
If you have a laptop with mobile GPUs, you can use powertop. Note that this work only on battery mode.

https://wiki.archlinux.org/index.php/powertop

You need to do calibration etc. see above page for more help.

**Comment by stigma0617** [comment]
@sacmehta many thanks !!

**Comment by sacmehta** [comment]
You need to very much familiar with Tx2 architecture, including register specification. Look for such details on NVIDIA’s page. It is not pretty straightforward for measuring power on TX2. If you think you are comfortable with computer architecture, please follow below thread to measure power on TX2:

https://devtalk.nvidia.com/default/topic/1000830/jetson-tx2-ina226-power-monitor-with-i2c-interface-/


Sorry, but I won’t be able to provide more help. Good luck

**Comment by sacmehta** [comment]
Also, while measuring power, make sure you restart your machine after every run and let it stay in idle position for about 5 minutes . This time window allows OS to finish startup related activities. To get a good estimate of power, Don’t launch any other process such as web browser while measuring power. Also, for each datapoint, repeat your experiments atleast 5 times to ensure that there is no variation in results.

For battery driven devices such as laptop and TX2, make sure that battery is fully charged (atleast 95%) before every run.
