### ISSUE TITLE
train.txt create

### ISSUE THREAD

**Issue by yuliang1995** [sacmehta/ESPNetv2#28]
Hi,I'm a beginner about machine learning.
How can i do for make train.txt.

Is using Dataload.py?
Which parameters should I change?

Can you provide a practice?

Thanks.

**Comment by yuliang1995** [comment]
and How to run gen_cityscapes?

**Comment by sacmehta** [comment]
Hi,

Thanks for your patience and interest in our code. We are about to release a new repository that supports several datasets (MS-COCO, ImageNet, PASCAL VOC, Cityscapes) across three different tasks (single/multi-label classification, object detection, and semantic segmentation). New repository includes better and fast training policies + scripts to set-up the datasets, including downloading and pre-processing. This repo should be out sometime next week.

I request you to wait for couple more days. 

Thanks
