### ISSUE TITLE
train/eval for another dataset

### ISSUE THREAD

**Issue by marcusvlc** [sacmehta/ESPNetv2#30]
Hello, how can I be training/evaluating the network for other datasets except imagenet? For exemple, for people classification or something like this? I tried to run the same command on README changing only the classes number on the model variable and changing the dataset path (my dataset is divided into train and val folders and each one with folders for classes)  and got some errors, can you help me? I want to use this network on raspberry pi.

**Comment by sacmehta** [comment]
See this repository: https://github.com/sacmehta/EdgeNets

It provides classification example on two datasets. You can adapt your case as per this repository
