### ISSUE TITLE
Question about predict on espnetv2

### ISSUE THREAD

**Issue by marcusvlc** [sacmehta/ESPNetv2#31]
How can I be using ESPNETv2 to make inferences on random images? In your repository and in the Edgenets repository I just found ways to evaluate in a specific dataset, but I would like to pass external images as a parameter and see the net result, how can I be doing this?

**Comment by sacmehta** [comment]
How hard is to adapt the test_segmentation.py file in the EdgeNets repository?

**Comment by marcusvlc** [comment]
A little difficult since I never use pytorch. I realized that you have the .onnx templates, would you have them in tensorflow .pb? I am trying to do this conversion with onnx but am having some errors:

ValueError: Dimensions must be equal, but are 32 and 112 for 'mul' (op: 'Mul') with input shapes: [32], [1,32,112,112].

**Comment by sacmehta** [comment]
I am not sure if we will have tensorflow .pb files in the near future. However, the mentioned error is because of incorrect mapping of the PRelu layer. Please ask on the appropriate forums
