### ISSUE TITLE
Network parameters of segmentation model in the paper

### ISSUE THREAD

**Issue by Jason93K** [sacmehta/ESPNetv2#34]
Thanks for your impressive work and code @sacmehta .
After I read your [ESPNetv2](http://openaccess.thecvf.com/content_CVPR_2019/papers/Mehta_ESPNetv2_A_Light-Weight_Power_Efficient_and_General_Purpose_Convolutional_Neural_CVPR_2019_paper.pdf) (CVPR'19) paper and previous versions on [arXiv,](https://arxiv.org/abs/1811.11431)
I have a question about the number of network parameters of segmentation model.

In Figure 7(c) of [v1](https://arxiv.org/abs/1811.11431v1) and [v2](https://arxiv.org/abs/1811.11431v2) papers, there are 2 models which have 725K, 99K parameters, respectively.
However, in Figure 7(a) of [v3](https://arxiv.org/abs/1811.11431) paper, there is a model that is more accurate than previous ones without the number of parameters.

Can you tell me the number of parameters of your model in Figure 7(a) of v3 paper?
Or the value of 's' which is scaling parameter in your model would be enough.
Thank you.

**Comment by sacmehta** [comment]
See here:
https://github.com/sacmehta/EdgeNets/blob/master/model/segmentation/model_zoo/README.md#pascal-voc-1

**Comment by Jason93K** [comment]
Thanks for really quick reply.
I used [this code](https://discuss.pytorch.org/t/how-do-i-check-the-number-of-parameters-of-a-model/4325/9) to count total parameters.
But when I set `EESPNet_Seg(classes=20, s=2.0)`, 
I got 1.25 million parameters, not 0.79 million as in [that table](https://github.com/sacmehta/EdgeNets/blob/master/model/segmentation/model_zoo/README.md#pascal-voc-1).
Do I need additional settings?

**Comment by sacmehta** [comment]
Are you using this model?
https://github.com/sacmehta/EdgeNets/blob/master/model/segmentation/espnetv2.py

**Comment by Jason93K** [comment]
No I was using https://github.com/sacmehta/ESPNetv2/blob/master/segmentation/cnn/SegmentationModel.py
I thought those are same.
Thanks!

**Comment by sacmehta** [comment]
This repository is obsolete. Please use EdgeNets going forward
