### ISSUE TITLE
Have you used ImageNet pretrained weight to train epsnetv2 for segmentation?

### ISSUE THREAD

**Issue by BaobeiChenchen** [sacmehta/ESPNetv2#35]
I want to check if the espnetv2 is trained with Imagenet pretrained weight. But it seems not clear in paper or the code. 

Looking forward to your reply.

**Comment by sacmehta** [comment]
Yes. However, we didn’t find much difference in performance between models trained from scratch and models initialized with ImageNet pretrained weights. Models trained from scratch took longer time for training.
