### ISSUE TITLE
What is the actual latency on ARM or CPU?

### ISSUE THREAD

**Issue by zeyu-liu** [sacmehta/ESPNetv2#5]
Thanks for the great work! And I also find that ESPNetv2 has comparable performance with MobileNet or ShuffleNet with even less FLOPS, but is the actual inference speed (images / sec) on ARM or CPU faster than the other light weighted architectures?

**Comment by sacmehta** [comment]
I have not tested on ARM devices, but it delivers comparable speed to otherwhile being more power efficient on other edge devices.

P.S: I am not sure if PyTorch has optimized libraries for CPU or ARM

**Comment by zeyu-liu** [comment]
Got it, thx for the reply :)
