### ISSUE TITLE
hi，when i train segmentation with two classes

### ISSUE THREAD

**Issue by zhangyunming** [sacmehta/ESPNetv2#7]
hi, when i run the segmentation  with two classes ,i get the error as below:
![default](https://user-images.githubusercontent.com/12590457/50756712-fddd2100-1297-11e9-827d-e92a74bbceb0.PNG)

**Comment by sacmehta** [comment]
It seems like you afe passing one argument as float to Conv layer. Could you print the values and check?

**Comment by tokyokuma** [comment]
I also faced the same problem.
This is caused by executing the code written in python3 with python2.
I do not know if this solution is correct, but for now, adding this one line to Model.py should resolve it.

Model.py
#print('Config: ', config)     #ln180
config = map(int, config)    #ln181 adding this line

I hope this method will work.

**Comment by zhangyunming** [comment]
hi，tokyokuma and sacmehta：

thank you very much for your reply, it is the reason of python2, and i can train the data of mine
but when i  change my data , and trained again, there is no model saved,and no information print
![image](https://user-images.githubusercontent.com/12590457/50875573-f20e6d80-1403-11e9-82b2-aa9f8dd2a055.png)

**Comment by tokyokuma** [comment]
The training seems to be able to be executed without problems.
The model has been updated every 1 epoch end.
Perhaps, have not you finished one epoch yet?
If you can train without problems
I think the model is saved in the following file.
segmentation / results_espnetv2_1.0 / model_best.pth

**Comment by zhangyunming** [comment]
> the model is saved in the following

yes,i have train several epoches, but there is no model saved in  /results_espnetv2_1.0

**Comment by tokyokuma** [comment]
Sorry, I have no idea at the moment.

**Comment by zhangyunming** [comment]
> Sorry, I have no idea at the moment.

thank you all the same 

but when i use 6 images to train , there is the model saved and the information print
![image](https://user-images.githubusercontent.com/12590457/50877496-1c185d80-140d-11e9-9135-5931c95155a2.png)

**Comment by zhangyunming** [comment]
just a whole epoch need train several times? like this:
![image](https://user-images.githubusercontent.com/12590457/50883080-e893fe00-1421-11e9-99cd-39ca7e95c7b4.png)

**Comment by zhangyunming** [comment]
ok
my falut.
thank you
