### ISSUE TITLE
Is there a problem here ?

### ISSUE THREAD

**Issue by monk42** [sacmehta/ESPNetv2#8]
https://github.com/sacmehta/ESPNetv2/blob/6c70184fb4cc4d64fac0f9ffb4b4f1a5b65c941f/segmentation/main.py#L209
The value of best_val  always be 0 , which means that model_best.pth stores not the best, but the last eopch!

**Comment by sacmehta** [comment]
It’s an error from my end. While cleaning the code, I accidentally removed one line. You can add below line before the line pointed by you. I will also fix it

best_val = max(mIOU_val, best_val)

**Comment by monk42** [comment]
Thanks，

**Comment by sacmehta** [comment]
This issue is fixed, so closing
