### ISSUE TITLE
I cannot get your accuracy after following your steps to train on the cisyscapes datase.

### ISSUE THREAD

**Issue by gao-ye** [sacmehta/ESPNetv2#9]
here is my result:
Epoch: 124	 Overall Acc (Tr): 0.8973	 Overall Acc (Val): 0.8530	 mIOU (Tr): 0.4831	 mIOU (Val): 0.4305
Per Class Training Acc: [0.9563952  0.87780535 0.9068668  0.43044552 0.5774933  0.5071546
 0.43101206 0.6368849  0.921697   0.7282442  0.9652385  0.788574
 0.32997596 0.94641626 0.22630975 0.26235422 0.14418961 0.17280169
 0.6403003  0.64186233]
Per Class Validation Acc: [0.9250288  0.7664717  0.9041689  0.2594584  0.4326968  0.47890368
 0.36922717 0.6052691  0.89565104 0.5700432  0.92304826 0.7061085
 0.36114156 0.89745665 0.21361473 0.30452752 0.04327752 0.09240897
 0.6547894  0.64558077]
Per Class Training mIOU: 
[0.93848205 0.6837373  0.826016   0.31308392 0.36571708 0.32630438
 0.29591504 0.4236251  0.853054   0.5105453  0.8888189  0.5311395
 0.23751496 0.84709704 0.18447216 0.21306016 0.12266205 0.13488355
 0.41068017 0.55468637]
Per Class Validation mIOU: 
[0.8795196  0.59463114 0.78535455 0.20169742 0.21248965 0.32275337
 0.2726844  0.45283318 0.82542694 0.3319856  0.82660824 0.43451232
 0.2278607  0.7965249  0.138431   0.2273348  0.02951417 0.07179707
 0.40751818 0.57027286]
and the miou can't be improved. 
I want to know  whether this situation happened while your training. Thanks a lot.

**Comment by sacmehta** [comment]
Cityscapes evaluation metric is different than the one in our codebase. Use their scripts and see how much you get. 

Train it for longer. It will improve.

**Comment by gao-ye** [comment]
What I use is just their script and after training 300 epoch ,the moiu on evaluation is still also around 0.43 while on the segmentation task . I find the miou on  several objects   is very low.

**Comment by gao-ye** [comment]
What I use is just their scripts and after training 300 epoch ,the moiu on evaluation is still also around 0.43 while on the segmentation task . I find the miou on  several objects   is very low.

**Comment by sacmehta** [comment]
Did you change any hyper parameters?

**Comment by gao-ye** [comment]
no

**Comment by sacmehta** [comment]
This is strange. I can share my log file tomorrow, if that helps.

**Comment by gao-ye** [comment]
I download the dataset, use their scripts to process the dataset, and follow the steps on your github. that's all.

**Comment by sacmehta** [comment]
By the way, which configuration  did you use?

**Comment by gao-ye** [comment]
OK. Thanks a lot.

**Comment by gao-ye** [comment]
pytorch version is 0.4.1.  s = 0.5.

**Comment by sacmehta** [comment]
could you test your results using Cityscapes evaluation scripts?

**Comment by gao-ye** [comment]
I hadn't do it. I will try it.

**Comment by sacmehta** [comment]
@gao-ye Are you able to reproduce the results?

**Comment by gao-ye** [comment]
no,i'm sorry.  i have no time and give up it. Anyhow, thanks a lot.

**Comment by sacmehta** [comment]
Here are the last few epoch results that were generated when I trained with s=0.5:

285		0.7747		0.5760		0.5005		0.4401		0.0000337
286		0.7819		0.5733		0.4993		0.4385		0.0000317
287		0.7726		0.5614		0.5022		0.4378		0.0000297
288		0.7717		0.5690		0.5025		0.4397		0.0000276
289		0.7764		0.5614		0.5015		0.4396		0.0000255
290		0.7663		0.5748		0.5022		0.4390		0.0000234
291		0.7748		0.5679		0.5006		0.4388		0.0000213
292		0.7735		0.5740		0.5004		0.4393		0.0000192
293		0.7671		0.5786		0.5047		0.4407		0.0000170
294		0.7693		0.5665		0.5009		0.4404		0.0000148
295		0.7672		0.5616		0.5034		0.4403		0.0000126
296		0.7679		0.5655		0.5018		0.4405		0.0000103
297		0.7650		0.5598		0.5041		0.4394		0.0000079
298		0.7761		0.5690		0.4998		0.4394		0.0000055
299		0.7698		0.5694		0.5047		0.4399		0.000003

**Comment by sacmehta** [comment]
These seems consistent with what you are getting. Testing using actual cityscapes evaluation scripts would give you the reported results.

**Comment by gao-ye** [comment]
ok, thank you.
